name: Push Forgejo Commit Status
description: Report job status as a commit status on a Forgejo instance. Sends a
  pending status when the step runs and automatically sends the final status as a
  post-job step.

inputs:
  token:
    description: Forgejo API token
    required: true
  host:
    description: Forgejo instance hostname (e.g. codeberg.org)
    required: false
    default: codeberg.org
  repository:
    description: Repository in owner/name format
    required: false
    default: ${{ github.repository }}
  sha:
    description: Commit SHA to set the status on
    required: false
    default: ${{ github.sha }}
  context:
    description: Unique identifier for this status check
    required: false
    default: ${{ github.workflow }} / ${{ github.job }}
  target_url:
    description: URL to link from the status
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  job_status:
    description: Workaround for getting the job status. Do not set manually
    default: ${{ job.status }}

runs:
  using: node24
  main: dist/index.js
  post: dist/post.js
  post-if: always()
