name: ci

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  github-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ./
        with:
          token: ${{ secrets.CODEBERG_TOKEN }}
